---
title: "R Notebook"
output: html_notebook
---

```{r}
tibble(p = c("tidyverse", "patchwork", "rethinking", "brms", "brms", "tidyverse", "patchwork", "tidybayes")) %>% 
  distinct(p) %>% 
  arrange(p)
```

```{r}
s %>% str()

sessionInfo()$otherPkgs$brms %>% str()


sessioninfo::session_info()$ packages$ package %>% str()

sessioninfo::package_info(include_base = F)

report::report_packages(include_R = F) %>% 
  summary() %>% 
  data.frame() %>% 
  rownames_to_column("package") %>% 
  select(package) %>% 
  arrange(package)


tibble(package = sessionInfo()$otherPkgs %>% names())


purrr::map_df(sessionInfo()$otherPkgs, function(x) x[])

sessionInfo()$otherPkgs %>% names()
```


```{r}
data.frame(packages = c(si1, si2))
```


```{r}
sort(names(sessionInfo()$otherPkgs))
```



```{r}
packages <- c("ape", "bayesplot", "brms", "broom", "dagitty", "devtools", "GGally", "ggdag", "ggdark", "ggrepel", "ggthemes", "ggtree", "ghibli", "gtools", "loo", "patchwork", "psych", "rcartocolor", "Rcpp", "remotes", "rethinking", "rstan", "StanHeaders", "statebins", "tidybayes", "tidyverse", "viridis", "viridisLite", "wesanderson")
```

```{r}
install.packages(packages, dependencies = T)
```

```{r}
devtools::install_github("stan-dev/cmdstanr")
devtools::install_github("EdwinTh/dutchmasters")
devtools::install_github("gadenbuie/ggpomological")
devtools::install_github("UrbanInstitute/urbnmapr")
remotes::install_github("stan-dev/posterior")
```




























